# Generated by Django 4.2 on 2023-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_selector',
            field=models.CharField(choices=[('PT', 'Product Stock'), ('CR', 'Color Stock'), ('SZ', 'Size Stock')], default='PT', max_length=2),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsize',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
    ]
